### ISSUE TITLE
Vereinfachen des Constructors

### ISSUE THREAD

**Issue by dermatthes** [c7lab/otto-db#1]
Hi,

versuch mal den Constructor über ein Trait wie folgt aufzurufen und die properties direkt aus dem Array zu setzen:

```
$obj = new SomeEntity([id=>"id", name="someName"]);
```

Das Entity soll dann nur so aussehen:

```
class SomeEntity
{
  use EntityTrait;

  public $id;
  public $name;
}
```

Also constructor ins Trait auslagern und wiederverwertbar machen.

Viele Grüße

**Comment by MariusVogel** [comment]
Hi, 

ist erledigt und getestet.
